const endpoint = {
  homedata: "/home/homedata.php",
  banner_product_list: "/home/banner_product_list.php",
  splash: "/home/splash.php",
  loginviagmailfacebook: "/user/save_user_masterbyapp.php",
  user_mobile_verification: "/user/save_user_masterbyapp.php",
  userlogin: "/user/save_user_masterbyapp.php",
  register: "/user/save_user_masterbyapp.php",
  set_password: "/user/save_user_masterbyapp.php",
  set_language: "/user/save_user_masterbyapp.php",
  set_pincode: "/user/save_user_masterbyapp.php",
  requestOTP: "/user/save_user_masterbyapp.php",
  cartaddeditdeleteitem: "/cartorder/cart_app.php",
  getCouponList: "/cartorder/cart_app.php",
  applyCoupon: "/cartorder/cart_app.php",
  cartlist: "/cartorder/cart_app.php",
  deletecartitem: "/cartorder/cart_app.php",
  getUserInfo: "/user/save_user_masterbyapp.php",
  regitserMobile: "/user/save_user_masterbyapp.php",
  wishlist: "/cartorder/cart_app.php",
  wishadd: "/cartorder/cart_app.php",
  wishdelete: "/cartorder/cart_app.php",
  editaddress: "/user/save_user_masterbyapp.php",
  placeOrder: "/cartorder/cart_app.php",
  getOrderDetails: "/cartorder/cart_app.php",
  canceledorder: "/home/ordermanage.php",
  canceled_order_product: "/home/ordermanage.php",
  history_order_productlist: "/home/ordermanage.php",
  current_order: "/home/ordermanage.php",
  current_order_productlist: "/home/ordermanage.php",
  orderdetail: "/home/ordermanage.php",
  
};
export default endpoint;
